// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Codiga.7f415e9f-9649-4ced-bbb2-64044b3d0a72";
        public const string Name = "Codiga";
        public const string Description = @"Code Snippets for 15+ languages and Code Analysis with Custom Rules.";
        public const string Language = "en-US";
        public const string Version = "0.0.8";
        public const string Author = "Codiga";
        public const string Tags = "";
    }
}
