// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Extension.2c544927-3588-41b4-9bfe-e80a0b99df80";
        public const string Name = "Extension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Malte Klapper";
        public const string Tags = "";
    }
}
