// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension.SnippetSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSnippetSearchPackageString = "e8d2d8f8-96dc-4c92-bb81-346b4d2318e4";
        public static Guid guidSnippetSearchPackage = new Guid(guidSnippetSearchPackageString);

        public const string guidSnippetSearchPackageCmdSetString = "e05530d0-618b-4eea-bbf7-49728865ebbd";
        public static Guid guidSnippetSearchPackageCmdSet = new Guid(guidSnippetSearchPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SnippetSearchCommandId = 0x0100;
    }
}