// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension.SnippetSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSnippetSearchPackageString = "e8d2d8f8-96dc-4c92-bb81-346b4d2318e4";
        public static Guid guidSnippetSearchPackage = new Guid(guidSnippetSearchPackageString);

        public const string guidSnippetSearchPackageCmdSetString = "e05530d0-618b-4eea-bbf7-49728865ebbd";
        public static Guid guidSnippetSearchPackageCmdSet = new Guid(guidSnippetSearchPackageCmdSetString);

        public const string guidImagesString = "8bb3f701-48db-4b56-81e9-137f2d5092f5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SnippetSearchCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}