name: Build and test reusable workflow

on: 
  workflow_call:
    inputs:
      config:
        type: string
        required: true
      collect-artifacts:
        type: boolean
        required: true
      version:
        type: string
        required: false

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update version
        if: inputs.version != ''
        uses: cezarypiatek/VsixVersionAction@1.0
        with:
          version: ${{ inputs.version }}
          vsix-manifest-file: src\Extension\source.extension.vsixmanifest

      - name: Commit new version
        if: inputs.version != ''
        uses: stefanzweifel/git-auto-commit-action@v4

      # using msbuild https://github.com/dotnet/sdk/issues/12421
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Solution
        run:  msbuild Extension.sln /restore /v:m /property:Configuration=${{ inputs.config }}

      - name: Install NUnit.ConsoleRunner
        run:  nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .   

      - name: Run UnitTests
        run:  ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  src\Tests\bin\${{ inputs.config }}\net48\Tests.dll     

      - name: Collect artifacts
        if: inputs.collect-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vs-extension
          path: bin\${{ inputs.config }}