name: Build and test on push

on: 
  push:
    # prevent normal build on tag push as this will be done by the release action
    tags-ignore:        
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      config: Debug
      collect-artifacts: false
