name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build Solution
        run: msbuild Extension.sln /t:Rebuild
        env: 
          DeployExtension: False
      - name: Install NUnit.ConsoleRunner
        run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .   
      - name: Run UnitTests
        run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  path/to/test.dll
    
