on:
  release:
    types:
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      config: Release
      collect-artifacts: true

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: vs-extension
          path: bin

      - name: Publish extension to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.1
        with:
          extension-file: 'bin\Extension.vsix'
          publish-manifest-file: 'publishManifest.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
      
    