on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ steps.latesttag.outputs.tag }}

      - name: Build release version
        uses: ./.github/workflows/build.yml
        with:
          config: Release
          collect-artifacts: true
          version: ${{ steps.semver.outputs.non-prefixed }}

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: vs-extension
          path: bin

      - name: Publish extension to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.1
        with:
          extension-file: 'bin\Extension.vsix'
          publish-manifest-file: 'publishManifest.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
      
    