on:
  release:
    types:
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      config: Release
      collect-artifacts: true

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get vsix file
      - uses: actions/download-artifact@v3
        with:
          name: vs-extension
          path: bin

      - name: Calculate next version
        uses: cezarypiatek/NextVersionGeneratorAction@0.4
        with:
          major-pattern: 'BREAKING CHANGES:'
          minor-pattern: 'FEATURE:'
          patch-pattern: '.*'
          output-to-env-variable: 'Version'

      - name: Set version for VSIX
        run: |
          $manifestPath = 'bin\Extension.vsix'
          $manifestXml = [xml](Get-Content $manifestPath -Raw)
          $manifestXml.PackageManifest.Metadata.Identity.Version = $env:Version
          $manifestXml.save($manifestPath)

      - name: Publish extension to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.1
        with:
          extension-file: 'bin\Extension.vsix'
          publish-manifest-file: 'publishManifest.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
      
    